import {
  BadgeCheck,
  Banknote,
  Building2,
  CalendarDays,
  ClipboardList,
  CreditCard,
  FileBarChart,
  Gift,
  Globe2,
  HandHeart,
  HeartHandshake,
  Landmark,
  LayoutDashboard,
  LifeBuoy,
  LockKeyhole,
  Mail,
  Megaphone,
  MonitorSmartphone,
  Phone,
  Receipt,
  ShieldCheck,
  Sparkles,
  Users,
  UserCog,
  WalletCards,
} from "lucide-react";

export const iconMap = {
  badgeCheck: BadgeCheck,
  banknote: Banknote,
  building: Building2,
  calendar: CalendarDays,
  clipboard: ClipboardList,
  creditCard: CreditCard,
  dashboard: LayoutDashboard,
  donation: Gift,
  globe: Globe2,
  handHeart: HandHeart,
  handshake: HeartHandshake,
  landmark: Landmark,
  lifeBuoy: LifeBuoy,
  lock: LockKeyhole,
  mail: Mail,
  megaphone: Megaphone,
  mobile: MonitorSmartphone,
  phone: Phone,
  receipt: Receipt,
  reports: FileBarChart,
  shield: ShieldCheck,
  sparkles: Sparkles,
  users: Users,
  userCog: UserCog,
  wallet: WalletCards,
};

export type IconKey = keyof typeof iconMap;
